### PR TITLE
change as_percent == FALSE to return total count

### PR DESCRIPTION
**Pull request by ceefluz**
Would be very useful to get the total count too. At first I expected this to be the result of as_percent == FALSE but realized it's only to return double. To me this change would make much sense :)

### CODE REVIEW

**Comment by ceefluz** [comment]
I think this is a little inconvenient. One function to get the proportion and the count through a logical argument would be nice, I think. 

Plus: Would be great to be able to pass several antimicrobials to the ab argument to not only check for two (ab1 and ab2). Would also work much better with shiny and RadaR ;) What do you think?

**Comment by msberends** [comment]
How could `ab` be multiple vectors then? Another thing I encountered during my blood culture analysis is that you often need `summarise_if` or `summarise_at`. That’s why I needed separate functions. For AMR analysis, you always want the percentages and the amount of isolates it was calculated from. That’s impossible with only one function in `summarise_*` functions.

**Comment by msberends** [comment]
And besides, if you have the total amount with `n_rsi`, why bother about amount of resistant isolates?
I like the examples of the `portion` help page, how it can calculate resistance and have the isolate count...

**Comment by msberends** [comment]
And if your column is of class `rsi`, you could easily use base R  multiple ways:

```r
sum(isolates == "R", na.rm = TRUE)
length(isolates[isolates == "R"])
```

**Comment by msberends** [comment]
What do you think of this: https://github.com/msberends/AMR/commit/3e87c8f409724c9bdb2e8abe00ecf7044bd7dcc1

😉

**Comment by msberends** [comment]
Check this out:

```r
septic_patients %>%
  select(amox, nitr, fosf, trim, cipr) %>%
  ggplot_rsi()

# get counts instead of percentages:
septic_patients %>%
  select(amox, nitr, fosf, trim, cipr) %>%
  ggplot_rsi(fun = count_df)
```

Or this:
```r
 septic_patients %>%
   select(amox, nitr, fosf, trim, cipr) %>%
   ggplot_rsi(fun = portion_df, facet = "ab", nrow = 1, position = "dodge")
```
image

compared to this (changed only `fun`):
```r
 septic_patients %>%
   select(amox, nitr, fosf, trim, cipr) %>%
   ggplot_rsi(fun = count_df, facet = "ab", nrow = 1, position = "dodge")
```
image

**Comment by msberends** [comment]
Ahhh, now I finally understand what you mean. Yes, good idea! I will implement it to support a data.frame as input.

**Comment by msberends** [comment]
> Plus: just added an alpha argument to geom_rsi and ggplot_rsi. Have a look. I like it :)

Where?

**Comment by ceefluz** [comment]
Should be a pull request with title: Adding alpha to geom_rsi and ggplot_rsi #1

**Comment by msberends** [comment]
*Ready while your wait* 
https://github.com/msberends/AMR/commit/da5379c881c2d498f51fdfb108f1fcd12a7697e3 😜 
```r
septic_patients %>% select(amox, cipr) %>% count_R()
# [1] 172

septic_patients %>% count_R(amox, cipr) # without select
# [1] 172

septic_patients %>% portion_IR(amox, cipr, gent) # endless
# [1] 0.09937888
```

Great ideas! They now works flawlessly. Just get the latest from GitHub.

**Pull request closed without merging**
